### ISSUE TITLE
Rename the repo to jupyterlab-app-cookiecutter

### ISSUE THREAD

**Issue by martinRenou** [jtpio/jupyterlab-app-template#19]
Should we rename this repo to `jupyterlab-app-cookiecutter`? Making it clearer that it's a cookiecutter

**Comment by jtpio** [comment]
Yes sounds good, thanks!

![image](https://user-images.githubusercontent.com/591645/161060457-a65de3a1-a75b-4308-990c-faa27902fb2f.png)
